module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        sidenav: '#FCFAF8',
        select_sidenav:"#feefe5",
        addbutton:"#c3412c",
        hover_sidenav : "#F2EFED",
        berry_red: '#B71C1C',
        red: '#FF0000',
        orange: '#FF9800',
        yellow: '#FFEB3B',
        olive_green: '#808000',
        lime_green: '#CDDC39',
        green: '#4CAF50',
        mint_green: '#98FF98',
        teal: '#008080',
        sky_blue: '#87CEEB',
        light_blue: '#ADD8E6',
        blue: '#0000FF',
        grape: '#6F2DA8',
        violet: '#8A2BE2',
        lavender: '#E6E6FA',
        magenta: '#FF00FF',
        salmon: '#FA8072',
        charcoal: '#36454F',
        grey: '#808080',
        taupe: '#483C32',
      },
    },
  },
  safelist: [
    'text-berry_red',
    'text-red',
    'text-orange',
    'text-yellow',
    'text-olive_green',
    'text-lime_green',
    'text-green',
    'text-mint_green',
    'text-teal',
    'text-sky_blue',
    'text-light_blue',
    'text-blue',
    'text-grape',
    'text-violet',
    'text-lavender',
    'text-magenta',
    'text-salmon',
    'text-charcoal',
    'text-grey',
    'text-taupe',
    

    'bg-berry_red',
    "bg-addbutton",
    'bg-red',
    'bg-orange',
    'bg-yellow',
    'bg-olive_green',
    'bg-lime_green',
    'bg-green',
    'bg-mint_green',
    'bg-teal',
    'bg-sky_blue',
    'bg-light_blue',
    'bg-blue',
    'bg-grape',
    'bg-violet',
    'bg-lavender',
    'bg-magenta',
    'bg-salmon',
    'bg-charcoal',
    'bg-grey',
    'bg-taupe',
    'bg-select_sidenav',
  ],
  plugins: [],
};
