const colorOptions = [
  { value: "Berry Red", color: "berry_red" },
  { value: "Red", color: "red" },
  { value: "Orange", color: "orange" },
  { value: "Yellow", color: "yellow" },
  { value: "Olive Green", color: "olive_green" },
  { value: "Lime Green", color: "lime_green" },
  { value: "Green", color: "green" },
  { value: "Mint Green", color: "mint_green" },
  { value: "Teal", color: "teal" },
  { value: "Sky Blue", color: "sky_blue" },
  { value: "Light Blue", color: "light_blue" },
  { value: "Blue", color: "blue" },
  { value: "Grape", color: "grape" },
  { value: "Violet", color: "violet" },
  { value: "Lavender", color: "lavender" },
  { value: "Magenta", color: "magenta" },
  { value: "Salmon", color: "salmon" },
  { value: "Charcoal", color: "charcoal" },
  { value: "Grey", color: "grey" },
  { value: "Taupe", color: "taupe" },
];
export default colorOptions;